### ISSUE TITLE
关于编译的问题提问

### ISSUE THREAD

**Issue by Seafoodair** [meshplus/hyperbench#43]
![image](https://user-images.githubusercontent.com/51044388/189920522-be566c48-18f0-47e5-a53f-ba12a245cf40.png)

**Comment by Seafoodair** [comment]
我尝试进行make build 但是出现了包错误，我是按照教程上进行的。不知道如何解决这个问题，希望您能看下，帮我解决这个问题。

**Comment by Varie-wtx** [comment]
你好，请问解决了吗？

**Comment by Seafoodair** [comment]
您发的邮件我已经收到谢谢
